#!/bin/bash
for ARG in "$@"; do
    echo -e "\033[32mStart install php $ARG\033[m"
    ver="php$ARG"
    sudo apt update
    sudo apt-get -y install $ver

    sudo apt-get -y install $ver-cli unzip
    sudo apt-get -y install $ver-gd
    sudo apt-get -y install $ver-zip
    sudo apt-get -y install $ver-xml
    sudo apt-get -y install $ver-curl
    sudo apt-get -y install $ver-mbstring
    sudo apt-get -y install $ver-mysql
    echo -e "\033[32mEnd install php $ARG\033[m"
done
